---
- hosts: default
  roles:
    - carlosbuenosvinos.ansistrano-deploy
  handlers:
    - nmae: restart mysql
      service:
        name: mysqld
        state: restarted
      become: yes
    - name: restart apache
      service:
        name: httpd
        state: restarted
      become: yes
    - name: restart samba
      service:
        name: smb
        state: restarted
      become: yes
